blog/urls.py
from django.urls import path
from blog import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('search/', views.SearchPostView.as_view(), name='search_result'),
    path('post/<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),

    path('dashboard/', views.DashBoardView.as_view(), name='dashboard'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),

    path('delete/<slug:slug>/', views.PostDeleteView, name='post_delete'),
    path('update/<slug:slug>/', views.PostUpdateView.as_view(), name='post_update'),
    path('profileupdate/<slug:slug>/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('like/<slug:slug>', views.Like_Post, name = 'like_post'),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from profiles import views
from django.contrib.auth import views as auth_views


app_name = 'profiles'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name=('profiles/login.html')), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name=('profiles/logout.html')), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from blog.views import CategoryViewSet,PostViewSet

router = routers.DefaultRouter()
router.register('category', CategoryViewSet)
router.register('post', PostViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('profiles/', include('profiles.urls')),
    path('api/', include(router.urls)),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
from django.utils.text import slugify
from profiles.models import Profile


class Post(models.Model):
    author = models.ForeignKey(Profile, related_name="posts", on_delete=models.CASCADE)
    title = models.CharField(max_length=1000)
    content = models.TextField()
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, max_length=2000)
    image = models.ImageField(default='post.jpg', upload_to='post_pics/')
    published_date = models.DateField(blank=True, null=True)
    category = models.ForeignKey('blog.category', on_delete=models.CASCADE)
    likes = models.ManyToManyField(Profile, blank=True, related_name="post_like")


    def likes_count(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.published_date = timezone.now()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, max_length=400)


    class Meta:
        verbose_name_plural = 'Categories'


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog/category_detail.html', kwargs={'slug':self.slug})

class Comments(models.Model):
    author = models.ForeignKey(Profile, related_name="comments", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=1000, blank=True)
    created_on = models.DateField(auto_now=True)


    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug':self.post.slug})

    class Meta:
        verbose_name = "comment"

blog/forms.py
from django import forms
from blog.models import Post, Category, Comments
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image','category')

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','username','password1','password2')



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('content',)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, TemplateView, FormView ,CreateView, DeleteView, UpdateView
from blog.models import Post, Category, Comments
from profiles.models import Profile
from profiles.forms import ProfileForm


from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from blog.forms import SignUpForm, PostForm, CommentForm
# from profiles.forms import
from django.contrib.auth.mixins import LoginRequiredMixin

# REST API IMPORT
from rest_framework import viewsets
from .serializers import CategorySerializer, PostSerializer
# Create your views here.


# Category mixins to show category in all pages
class CategoryMixin(object):
    def get_categories(self):
        return Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CategoryMixin, self).get_context_data(**kwargs)
        context['categories'] = self.get_categories()
        return context


# displays all posts
class PostListView(CategoryMixin, ListView):
    context_object_name = 'posts'
    model = Post
    paginate_by = 8
    template_name = 'blog/post_list.html'

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        tPosts = Post.objects.filter(likes__gt=0)
        context['tPosts'] = tPosts
        context['post_form'] = PostForm
        return context



# creating post
class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = 'profiles:login'
    template_name = 'blog/base.html'
    form_class = PostForm
    success_url = reverse_lazy('post_list')


    def form_valid(self, form):
        post_form = form.save(commit=False)
        post_form.author = self.request.user.profile
        post_form.save()
        return super(PostCreateView, self).form_valid(form)

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    form_class = ProfileForm
    model = Profile
    template_name = 'dashboard/profile_form.html'
    success_url = reverse_lazy('dashboard')


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    form_class = PostForm
    model = Post
    template_name = 'dashboard/post_form.html'
    success_url = reverse_lazy('dashboard')


# displays posts by category
class CategoryDetailView(CategoryMixin,DetailView):
    context_object_name = 'category'
    model = Category
    template_name = 'blog/category_detail.html'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context =super(CategoryDetailView, self).get_context_data(**kwargs)
        cat_posts = self.get_cat_posts()
        tPosts = Post.objects.filter(likes__gt=0)
        context['cat_posts'] = cat_posts
        context['tPosts'] = tPosts
        context['page_obj'] = cat_posts
        context['post_form'] = PostForm
        return context

    def get_cat_posts(self):
        queryset = self.get_categories()
        paginator = Paginator(queryset,8)
        page = self.request.GET.get('page')
        cat_posts = paginator.get_page(page)
        return cat_posts


# search for post
class SearchPostView(CategoryMixin, ListView):
    context_object_name = 'posts'
    model = Post
    template_name = 'blog/search_post_list.html'

    def get_context_data(self, **kwargs):
        context = super(SearchPostView, self).get_context_data(**kwargs)
        s_posts = self.get_posts()
        tPosts = Post.objects.filter(likes__gt=0)
        context['tPosts'] = tPosts
        context['post_form'] = PostForm
        context['s_posts'] = s_posts
        context['page_obj'] = s_posts
        return context

    def get_posts(self):
        search = self.request.GET.get('q')
        if search != '' and search is not None:
            searched = Post.objects.filter(title__icontains=search)
        queryset = searched
        paginator = Paginator(queryset, 8)
        page = self.request.GET.get('page')
        s_posts = paginator.get_page(page)
        return s_posts


# displays post detail
class PostDetailView(CategoryMixin, DetailView):
    context_object_name = 'post'
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comments'] = Comments.objects.all()
        tPosts = Post.objects.filter(likes__gt=0)
        context['tPosts'] = tPosts
        context['form'] = CommentForm
        context['post_form'] = PostForm
        return context

    # create comment in post detailview
    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        comment_form = form.save(commit=False)
        if form.is_valid():
            post = self.get_object()
            comment_form.author = self.request.user.profile
            comment_form.post = post
            comment_form.save()

            return redirect(reverse("post_detail", kwargs={'slug':post.slug}))



# user dashboard for CRUD operations
class DashBoardView(LoginRequiredMixin, CategoryMixin, ListView):
    login_url = 'profiles:login'
    template_name = 'dashboard/dpost_list.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super(DashBoardView, self).get_context_data(**kwargs)
        d_posts = self.get_dposts()
        context['d_posts'] = d_posts
        # context['page_obj'] = d_posts
        context['post_form'] = PostForm
        return context

    def get_dposts(self):
        d_posts = Post.objects.filter(author_id=self.request.user.profile)

        return d_posts


@login_required
def PostDeleteView(request, slug):
    post = get_object_or_404(Post, slug=slug)
    post.delete()
    return redirect(reverse('dashboard'))


# like post functionality
@login_required
def Like_Post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    is_liked = False
    if post.likes.filter(id=request.user.profile.id).exists():
        post.likes.remove(request.user.profile)
        is_liked = False
    else:
        post.likes.add(request.user.profile)
        is_liked = True
    return HttpResponseRedirect(reverse('post_detail' , kwargs={'slug':post.slug}))


#REST API
class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}


<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="#">Frendzy <span class="text-primary">Blog</span></a>


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navmenu">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'post_list' %}">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Create Post</a>
                <li class="nav-item"><a class="nav-link" href="{% url 'profiles:logout' %}">Logout</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'post_list' %}">Posts</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'profiles:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'profiles:signup' %}">Sign Up</a></li>
                {% endif %}

                <li class="nav-item">
                    <div>
                        <form method="GET" action="{% url 'search_result' %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <input class="form-control" name="q" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="submit">Search</button>
                            </div>
                        </form>
                    </div>
                </li>
            </ul>
        </div>

    </div>
</nav>


<body>

<div class="container main-container mt-4">
    <section class="page-section">


        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog content">
            <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"><b>Create Post</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>

              <div class="modal-body">
                <form method="post" enctype="multipart/form-data" action="{% url 'post_create' %}">
                    {% csrf_token %}

                    {{ post_form | crispy }}

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" value="Post">
                    </div>
                </form>
              </div>


            </div>
          </div>
        </div>

    <div class="row">

        <!-- Blog entries-->
        <div class="col-lg-8">

            <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
                <div class="container">


                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#category">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    {% for category in categories %}
                    <div class="collapse navbar-collapse" id="category">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item mt-2">
                                <a class="nav-link" href="{% url 'category_detail' slug=category.slug %}">{{ category.name }} <span class="badge badge-light">{{ category.post_set.all.count }}</span></a></li>
                        </ul>
                    </div>
                    {% endfor %}

                </div>
            </nav>
            {% block content %}

            {% endblock %}


            <!-- Side widgets-->
            <div class="col-lg-4">
                <!-- Categories widget-->

                {% if post %}
                <div class="card content mb-4">
                    <div class="card-header bg-dark text-light">Related Posts</div>
                    <div class="card-body">
                        <ul>
                            {% for post in post.category.post_set.all %}
                            <li><p><a class="text-decoration-none text-dark" href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></p></li>
                            {% endfor %}
                        </ul>


                    </div>
                </div>
                {% endif %}


                {% if tPosts %}
                <div class="card content mb-4">
                    <div class="card-header bg-dark text-light">Trending Posts</div>
                    <div class="card-body">
                        <ul>
                            {% for post in tPosts %}
                            <li><p><a class="text-decoration-none text-dark" href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></p></li>
                            {% endfor %}
                        </ul>


                    </div>
                </div>
                {% endif %}


                <!-- Side widget-->
<!--                <div class="card sidebar mb-4">-->
<!--                    <div class="card-header bg-dark text-light">Side Widget</div>-->
<!--                    <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>-->
<!--                </div>-->
            </div>
        </div>
    </div>

    </section>
</div>

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Frendzy <span class="text-primary">Blog</span> 2021</p></div>
        <div class="container"><p class="m-0 text-center text-white">Disclaimer: Every Frendzy <span class="text-primary">Blog</span> member is solely responsible for anything that he/she posts or uploads on Frendzy <span class="text-primary">Blog</span>.
        </p></div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
            crossorigin="anonymous">
    </script>
    <script>
    //CheckBox Selection
    function checkCat(checkbox) {
        var checkboxes = document.getElementsByName('category');
        checkboxes.forEach((item) => {
          if (item !== checkbox) item.checked =  false
        })
    }

    </script>

</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
{% if user.username %}
    {{ user.username|title }}'s Blog
    {% else %}
Frendzy <span class="text-primary">Blog</span>
{% endif %}

{% endblock %}


{% block content %}

<div class="row justify-content-left mt-2">
    <div class="col-8">
        <h1 class="mt-2"><b>{{ category.name }}</b></h1>
      <hr class="mt-0 mb-2">
    </div>
</div>

        {% for post in category.post_set.all %}
        <div class="card content mt-2">

            <div class="row">
                    <div class="col-md-4">
                        {% if post.image %}
                        <div class="post-image">
                            <a href="{% url 'post_detail' slug=post.slug %}"><img class="card-img-top" src="{{ post.image.url }}" height="200px" width="200px" alt="image.png"></a>
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                            <div class="card-body">
                                <a class="text-decoration-none text-dark" href="{% url 'post_detail' slug=post.slug %}">
                                <div class="small text-muted">posted by {{ post.author.user.username| title }} on {{ post.published_date }} - {{post.category}} </div>
                                <h2 class="card-title h4">{{ post.title }}</h2>
                                <p class="card-text">{{ post.content|safe|truncatechars:200 }}</p>
                                <p class="card-text mt-4 post-icons"><i class="fa fa-heart like"></i> {{ post.likes.count }}  <i class="fa fa-comments"> {{ post.comments.count }} </i></p>
                                </a>
                            </div>
                    </div>
            </div>
        </div>
        {% empty %}
        <div class="card content mt-2">
            <div class="card-body">
                <h3 class="card-title text-center"><b>No post to display</b></h3>
                <img class="rounded mx-auto d-block" src="{% static 'assets/empty.png' %}" height="50%" width="50%" />
                {% if user.is_authenticated %}
                <h5 class="card-title text-center"><b>Be the first to <a href="#" class="text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">create a post</a></b></h5>
                {% else %}
                <h5 class="card-title text-center"><b><a class="text-decoration-none" href="{% url 'profiles:login' %}">Login to create post</a></b></h5>
                {% endif %}
            </div>
        </div>

        {% endfor %}



    {% if category.post_set.all %}
    <nav aria-label="Pagination">
        <hr class="my-0" />
        <ul class="pagination justify-content-center my-4">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page.number }}" tabindex="-1" aria-disabled="true">Previous</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
            {% endif %}
            <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

blog/templates/blog/dashboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Home - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Dashboard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'post_list' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>


        <!-- Page content-->
        <div class="container">
            <div class="row py-5">

                <!-- Blog entries-->
                <div class="col-lg-8">
                    <div class="row justify-content-left">
                        <div class="col-8">
                          <h1 class="mt-2">Posts</h1>
                          <hr class="mt-0 mb-4">
                        <a class="btn btn-primary my-3" href="#">Create Post</a>

                        </div>
                    </div>


                    {% for post in posts %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="small text-muted">Published on {{ post.published_date }} posted by {{ post.author.username }}</div>
                            <h2 class="card-title">{{ post.title }}</h2>
                            <a class="btn btn-primary" href="#">View</a>
                            <a class="btn btn-primary" href="#">Update</a>
                            <a class="btn btn-primary" href="#">Delete</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!-- Pagination-->
<!--                {% if posts %}-->
<!--                <nav aria-label="Pagination">-->
<!--                    <hr class="my-0" />-->
<!--                    <ul class="pagination justify-content-center my-4">-->
<!--                        {% if page_obj.has_previous %}-->
<!--                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page.number }}" tabindex="-1" aria-disabled="true">Previous</a></li>-->
<!--                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>-->
<!--                        {% endif %}-->
<!--                        <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>-->
<!--                        {% if page_obj.has_next %}-->
<!--                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>-->
<!--                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>-->
<!--                        {% endif %}-->
<!--                    </ul>-->
<!--                </nav>-->
<!--                {% endif %}-->




                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <form class="form-control" method="GET" action="{% url 'search_result' %}">
                                {% csrf_token %}
                            <div class="input-group">
                                <input class="form-control" name="q" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="submit">Go!</button>
                            </div>
                            </form>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                {% for category in categories %}
                                <div class="col-sm-6 text-center">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="{% url 'category_detail' slug=category.slug %}">{{ category.name }}</a></li>

                                    </ul>
                                </div>
                                {% endfor %}
                                <br>
                                <a class="btn btn-primary" href="#">Add Category</a>


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>